# Generated by Django 4.1.10 on 2023-07-26 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelcssclass',
            name='css_code',
        ),
        migrations.RemoveField(
            model_name='modelcssclass',
            name='icon_url',
        ),
        migrations.AddField(
            model_name='modelcssclass',
            name='css_class',
            field=models.CharField(default='', max_length=50, verbose_name='CSS Class Code'),
        ),
        migrations.AddField(
            model_name='modelcssclass',
            name='icon',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Icon URL'),
        ),
        migrations.AlterField(
            model_name='modelcssclass',
            name='description',
            field=models.TextField(default='', verbose_name='Description'),
            preserve_default=False,
        ),
    ]
