# Generated by Django 4.1.10 on 2023-07-28 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_modelcssclass_css_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelcssclass',
            old_name='css_class',
            new_name='css_code',
        ),
        migrations.RemoveField(
            model_name='modelpostcontent',
            name='css_class',
        ),
        migrations.RemoveField(
            model_name='modelpostcontent',
            name='media_css_class',
        ),
        migrations.RemoveField(
            model_name='modelpostcontent',
            name='text_css_class',
        ),
        migrations.AddField(
            model_name='modelcssclass',
            name='css_type',
            field=models.CharField(choices=[('text', 'Text'), ('media', 'Media')], default='text', max_length=10, verbose_name='CSS Class Type'),
        ),
        migrations.AddField(
            model_name='modelpostcontent',
            name='css_media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_content', to='blog.modelcssclass', verbose_name='CSS Class for Media'),
        ),
        migrations.AddField(
            model_name='modelpostcontent',
            name='css_text',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='text_content', to='blog.modelcssclass', verbose_name='CSS Class for Text'),
        ),
        migrations.AlterField(
            model_name='modelcssclass',
            name='name',
            field=models.CharField(max_length=50, verbose_name='CSS_Name'),
        ),
    ]
