# Generated by Django 4.1.10 on 2023-07-31 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_css_class_modelcssclass_css_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelcssclass',
            name='css_code',
        ),
        migrations.RemoveField(
            model_name='modelcssclass',
            name='name',
        ),
        migrations.AddField(
            model_name='modelcssclass',
            name='class_css',
            field=models.CharField(default='', max_length=50, verbose_name='CSS Class'),
        ),
        migrations.AddField(
            model_name='modelcssclass',
            name='class_css_code',
            field=models.TextField(default=1, verbose_name='Код Class-CSS'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modelcssclass',
            name='name_css_class',
            field=models.CharField(default='', max_length=50, verbose_name='Класс CSS (название)'),
        ),
        migrations.AlterField(
            model_name='modelcssclass',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
    ]
