# Generated by Django 4.1.10 on 2023-08-08 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_modelcssclass_css_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelposts',
            name='user_first_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='User First Name'),
        ),
        migrations.AddField(
            model_name='modelposts',
            name='user_last_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='User Last Name'),
        ),
        migrations.AddField(
            model_name='modelposts',
            name='user_username',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='User Username'),
        ),
    ]
