# Generated by Django 4.1.10 on 2023-08-14 15:48

import blog.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_modelposts_user_first_name_modelposts_user_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelpostcontent',
            name='css_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image_content', to='blog.modelcssclass', verbose_name='CSS Class for Image'),
        ),
        migrations.AddField(
            model_name='modelpostcontent',
            name='image_file',
            field=models.FileField(blank=True, null=True, upload_to=blog.utils.get_image_file_path),
        ),
        migrations.AlterField(
            model_name='modelcssclass',
            name='css_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('code', 'Code'), ('youtube', 'YouTube'), ('audio', 'Audio'), ('media', 'Media')], default='text', max_length=10, verbose_name='CSS Class Type'),
        ),
        migrations.AlterField(
            model_name='modelpostcontent',
            name='content_text',
            field=models.TextField(blank=True, null=True, verbose_name='Часть текста поста'),
        ),
    ]
