# Generated by Django 4.1.10 on 2023-08-14 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_modelpostcontent_css_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelpostcontent',
            name='css_youtube',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='youtube_content', to='blog.modelcssclass', verbose_name='CSS Class for YouTube Video'),
        ),
        migrations.AddField(
            model_name='modelpostcontent',
            name='youtube_video',
            field=models.URLField(blank=True, null=True, verbose_name='YouTube Video URL'),
        ),
        migrations.AlterField(
            model_name='modelpostcontent',
            name='content_text',
            field=models.TextField(blank=True, null=True, verbose_name='Post Text Part'),
        ),
    ]
