# Generated by Django 4.1.10 on 2023-08-14 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_modelpostcontent_css_youtube_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelpostcontent',
            name='youtube_iframe',
            field=models.TextField(blank=True, help_text='Insert the YouTube embed code (iframe).', null=True, verbose_name='YouTube Embed Code'),
        ),
    ]
