# Generated by Django 4.1.10 on 2023-08-18 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_modelpostcontent_youtube_iframe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelpostcontent',
            name='youtube_iframe',
        ),
    ]
