# Generated by Django 4.1.10 on 2023-08-18 12:16

import blog.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_modelpostcontent_youtube_iframe'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelpostcontent',
            name='code',
            field=models.TextField(blank=True, null=True, verbose_name='Code'),
        ),
        migrations.AddField(
            model_name='modelpostcontent',
            name='css_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='code_content', to='blog.modelcssclass', verbose_name='CSS Class for Code'),
        ),
        migrations.AlterField(
            model_name='modelpostcontent',
            name='image_file',
            field=models.FileField(blank=True, null=True, upload_to=blog.utils.get_image_file_path, verbose_name='Post Image Part'),
        ),
        migrations.AlterField(
            model_name='modelpostcontent',
            name='media_file',
            field=models.FileField(blank=True, null=True, upload_to=blog.utils.get_media_file_path, verbose_name='Post Media Part'),
        ),
    ]
